version: "3.8"
services:

  server:
    depends_on:
      - db
    build:
      context: ./server
    image: server:latest
    ports:
      - 5000:5000
    networks:
      diary_task:
    hostname: "server.local"
    container_name: "server_diary"
    command: "npm run start:dev"

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
    networks:
      diary_task:
    hostname: "db_postgres.local"
    container_name: "db_postgres_diary"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./server/.env
    ports:
      - 3002:80
    networks:
      diary_task:

networks:
  diary_task: