version: "3.8"
services:
  client:
    depends_on:
      - server
    build:
      context: ./client
    image: client:latest
    ports:
      - 8000:3000
    networks:
      diary:
    hostname: "client.local"
    container_name: "client"
    command: "npm start"

  server:
    depends_on:
      - db
    build: 
      context: ./server
    image: server:latest
    ports:
      - 5000:5000
    networks:
      diary:
    hostname: "server.local"
    container_name: "server"
    command: "npm run start:dev"

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: null
      MONGO_INITDB_ROOT_PASSWORD: null
    ports:
      - 27017:27017
    networks:
      diary:
    hostname: "db_mongo.local"
    container_name: "db_mongo"

networks:
  diary: